In [1]:
%matplotlib inline

In [2]:
import pandas as pd
import numpy as np

from sklearn import metrics

In [7]:
docs=pd.read_csv("Train1 file.csv")

In [8]:
docs.head(5)

Document      Class
0      Greatlakes is a great educational institution  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholay is a great cinema     cinema
4                   Good movie depends on good story     cinema

In [9]:
docs['Class'] = docs.Class.map({'cinema':0,'education':1})

In [20]:
numpy_array=docs.as_matrix()

X=numpy_array[:,0]
Y=numpy_array[:,1]
Y=Y.astype('int')
print(X)
print(Y)

['Greatlakes is a great educational institution'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholay is a great cinema' 'Good movie depends on good story']
[1 1 1 0 0]


C:\Users\91979\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [11]:
from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer()

In [12]:
vec.fit(X)
vec.vocabulary_

{'greatlakes': 7,
 'is': 10,
 'great': 6,
 'educational': 3,
 'institution': 9,
 'greatness': 8,
 'depends': 2,
 'on': 13,
 'ethics': 4,
 'story': 15,
 'of': 12,
 'and': 0,
 'sholay': 14,
 'cinema': 1,
 'good': 5,
 'movie': 11}

In [17]:
vec=CountVectorizer(stop_words='english')
vec.fit(X)
vec.vocabulary_

{'greatlakes': 6,
 'great': 5,
 'educational': 2,
 'institution': 8,
 'greatness': 7,
 'depends': 1,
 'ethics': 3,
 'story': 11,
 'sholay': 10,
 'cinema': 0,
 'good': 4,
 'movie': 9}

In [18]:
X_transformed=vec.transform(X)
X_transformed

<5x12 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [19]:
print(X_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 6)	1
  (0, 8)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 7)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 7)	1
  (2, 11)	1
  (3, 0)	1
  (3, 5)	1
  (3, 10)	1
  (4, 1)	1
  (4, 4)	2
  (4, 9)	1
  (4, 11)	1


In [21]:
X_transformed = vec.transform(X)
X_transformed

<5x12 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [22]:
print(X_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 6)	1
  (0, 8)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 7)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 7)	1
  (2, 11)	1
  (3, 0)	1
  (3, 5)	1
  (3, 10)	1
  (4, 1)	1
  (4, 4)	2
  (4, 9)	1
  (4, 11)	1


In [23]:
X=X_transformed.toarray()
X

array([[0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [24]:
#convert matrix into DataFrame
pd.DataFrame(X, columns = vec.get_feature_names())

cinema  depends  educational  ethics  good  great  greatlakes  greatness  \
0       0        0            1       0     0      1           1          0   
1       0        1            1       1     0      0           0          1   
2       0        0            1       1     0      1           0          1   
3       1        0            0       0     0      1           0          0   
4       0        1            0       0     2      0           0          0   

   institution  movie  sholay  story  
0            1      0       0      0  
1            0      0       0      0  
2            0      0       0      1  
3            0      0       1      0  
4            0      1       0      1

This table shows how many times aparticular word occurs in a document.

A corpus of documents can be represented by a matrix with one row per document and one column per token occuring in the corpus

Vectorization is a process of tuning a collection of text document into numerical feature vectors. This specific strategy is called Bag of wordws representation

Steps for Vectorization

Import

Instantiate

Fit

Transform

In [27]:
test_doc = pd.read_csv("Test1 file.csv")
test_doc

Document      Class
0  Greatlakes is a great educational institution  education

In [28]:
test_doc['Class'] = test_doc.Class.map({'cinema':0, 'education':1})
test_doc

Document  Class
0  Greatlakes is a great educational institution      1

In [29]:
test_numpy_array = test_doc.as_matrix()

X_test=test_numpy_array[:,0]
y_test=test_numpy_array[:,1]
print(X_test)
print(y_test)

['Greatlakes is a great educational institution']
[1]


C:\Users\91979\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [30]:
X_test_transformed = vec.transform(X_test)
X_test_transformed

<1x12 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [31]:
print(X_test_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 6)	1
  (0, 8)	1


In [32]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0]], dtype=int64)

# Multinomial Naive Bayes

In [33]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

In [34]:
mnb.fit(X,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [35]:
proba = mnb.predict_proba(X_test)
print("Probability of test document belonging to Cinema ", proba[:,0])
print("Probability of test document belonging to Education ", proba[:,1])

Probability of test document belonging to Cinema  [0.06350981]
Probability of test document belonging to Education  [0.93649019]


In [36]:
pd.DataFrame(proba, columns = ['Cinema','Education'])


Cinema  Education
0  0.06351    0.93649

# Bernoulli Naive Bayes

In [37]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()

In [38]:
bnb.fit(X,Y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [39]:
proba1=bnb.predict_proba(X_test)

In [40]:
pd.DataFrame(proba1, columns = ['Cinema','Education'])


Cinema  Education
0  0.024641   0.975359